version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - cd src/server
      - pip install -r requirements.txt -t dependencies
  build:
    commands:
      - zip -r dependencies.zip dependencies/
      - zip -r function.zip index.py
artifacts:
  files:
    - dependencies.zip
    - function.zip
  discard-paths: yes
  base-directory: src/server