image: gitpod/workspace-full

tasks:
  - init: |
      echo "Setting up Python environment..."
      cd src/server
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pip install pytest
      deactivate

      echo "Setting up Node.js dependencies..."
      cd ../client-frontend
      npm install

      echo "Installing AWS CLI..."
      sudo apt update && sudo apt install awscli -y

      echo "Setting up AWS credentials..."
      mkdir -p ~/.aws
      echo "[default]" > ~/.aws/credentials
      echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      echo "[default]" > ~/.aws/config
      echo "region=us-east-1" >> ~/.aws/config

  - command: |
      source venv/bin/activate
      echo "Virtual environment activated!"
      export AWS_PROFILE=default
      aws sts get-caller-identity