AWSTemplateFormatVersion: '2010-09-09'
Description: Main Template for Workload Application Resources

Parameters:
  Environment:
    Type: String
    Default: Dev
    Description: Environment name for the VPC

Resources:
  ### Include S3 and Lambda Resources ###
  S3AndLambdaResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3_lambda_template.yaml
      Parameters:
        Environment: !Ref Environment

  ### Include DynamoDB Resources ###
  DynamoDBResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamodb_template.yaml
      Parameters:
        Environment: !Ref Environment

Outputs:
  ClientBucketName:
    Value: !GetAtt S3AndLambdaResources.Outputs.ClientBucketName
    Description: "S3 Bucket for the client application"

  LogBucketName:
    Value: !GetAtt S3AndLambdaResources.Outputs.LogBucketName
    Description: "S3 Bucket for logs"

  LambdaFunctionArn:
    Value: !GetAtt S3AndLambdaResources.Outputs.LambdaFunctionArn
    Description: "Lambda function ARN"

  AdminTableName:
    Value: !GetAtt DynamoDBResources.Outputs.AdminTableName
    Description: "DynamoDB Table for admin data"
