AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table for Admin Data

Parameters:
  Environment:
    Type: String
    Default: Dev
    Description: Environment name for the VPC

Resources:
  ### DynamoDB Table for Admin Data ###
  AdminTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AdminTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  AdminTableName:
    Value: !Ref AdminTable
    Description: "DynamoDB Table for admin data"
