name: Detect Changes in Server and Run Script

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  check-changes-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Detect changes in src/server
        id: detect-changes
        run: |
          echo "Detecting changes in the src/server folder..."

          BASE_COMMIT=$(git merge-base origin/main HEAD)
          
          if git diff --name-only $BASE_COMMIT HEAD | grep '^src/server/' > changes_detected.txt; then
            echo "Changes detected in src/server."
            echo "should_run=true" >> $GITHUB_ENV
          else
            echo "No changes detected in src/server."
            echo "should_run=false" >> $GITHUB_ENV
          fi

      - name: Run upload-server.sh
        if: env.should_run == 'true'
        run: |
          echo "Running upload-server.sh..."
          chmod +x src/bin/upload-server.sh
          src/bin/upload-server.sh
